### ISSUE TITLE
Changes I had to make to send email over TLS via hostmonster.com v0.4.0

### ISSUE THREAD

**Issue by damianham** [arcage/crystal-email#62] opened 2020-04-12 17:11 UTC
I had issues sending email over TLS via hostmonster.com but sending email with Evolution email client worked fine.  Using wireshark I was able to determine that Evolution started the TLS session immediately before and SMTP protocol e.g. before sending HELO.  These are the changes I had to make to client.cr to get it to work (with hostmonster).
```
  def start
    ready_to_send
    if @config.use_tls? && smtp_starttls && smtp_helo
      smtp_auth
      @started = true
      with self yield
      @started = false
      smtp_quit
    else
      if smtp_helo && smtp_auth
        @started = true
        with self yield
        @started = false
      else
        log_error("Failed in connecting for some reason")
      end
      smtp_quit
    end
  rescue error
    fatal_error(error)
  ensure
    begin
      close_socket
    rescue error
      fatal_error(error)
    end
  end
.....
private def smtp_helo
    status_code, status_messages = smtp_command("EHLO", helo_domain)
    if status_code == "250"
      status_messages.each do |status_message|
        message_parts = status_message.strip.split(' ')
        command = message_parts.shift
        @esmtp_commands[command] = message_parts
      end
      true
    elsif status_code == "220"
      status_code, status_messages = smtp_responce("CONN")
      status_messages.each do |status_message|
        message_parts = status_message.strip.split(' ')
        command = message_parts.shift
        @esmtp_commands[command] = message_parts
      end
      true
    elsif status_code == "502"
      status_code, _ = smtp_command("HELO", helo_domain)
      status_code == "250"
    end
  end
```

Also I HAD to pass in **helo_domain** as __socket.as(TCPSocket)__ threw a cast exception.

**Comment by damianham** [comment] 2020-04-12 17:14
And also this change
```
private def smtp_starttls
    if @config.use_tls?
      log_info("start TLS")
      {% if flag?(:without_openssl) %}
          log_error("TLS is disabled because `-D without_openssl` was passed at compile time")
          false
      {% else %}
        log_info("create openssl socket.client")
        tls_socket = OpenSSL::SSL::Socket::Client.new(@socket.as(TCPSocket), @config.tls_context, sync_close: true, hostname: @config.host)
        tls_socket.sync = false
        log_info("Start TLS session with #{tls_socket.tls_version}")
        @socket = tls_socket
      {% end %}
    else
      true
    end
  end
```

**Comment by arcage** [comment] 2020-04-13 02:32
Because the port number is 465, it seems that the hostmonster uses SMTPS(SMTP over SSL/TLS), not STARTTLS.

Those two SMTP encryption methods have different timing to encrypt its connection.

- SMTPS starts the SMTP with already SSL/TLS encrypted connection.
- STARTTLS starts the SMTP connection without encryption, then upgrades it to use encryption.

Although the current version of this shard supports STARTTLS only, I will try to implement SMTPS mode on this shard based on your work around.

Thank you very much for your suggestion.

**Comment by damianham** [comment] 2020-04-13 04:31
It seems like a good idea to make helo_domain a required config item and also to add a config item to indicate SMTPS or STARTTLS.

Thanks very much for your excellent work.

**Comment by arcage** [comment] 2020-04-18 05:53
I released v0.6.0 with SMTPS support.

You can use it by `usr_tls: :smtps` argument in `EMail::Client::Config.create` method or using `config.use_tls(:smtps)`

Could you test it?

**Comment by damianham** [comment] 2020-04-18 08:11
Yes I will test as soon as I have a chance.

**Comment by arcage** [comment] 2020-05-07 07:23
I will close this issue once.

Please reopen this when the problem is unsolved.

**Closed as completed** 2020-05-07 07:23 UTC
